create table discente (
        rm varchar(6),
        id bigint generated by default as identity,
        id_pessoa bigint,
        nivel enum ('A_DEFINIR','BACHARELADO','DOUTORADO','ESPECIALIZACAO','MBA','MESTRADO','TECNICO','TECNOLOGO'),
        status enum ('ATIVO','A_DEFINIR','BLOQUEADO','CANCELADO','EM_MOBILIDADE','FORMADO','INATIVO','TRANCADO'),
        primary key (id)
    );
 
    create table funcao (
        id bigint generated by default as identity,
        nome enum ('ADMIN','COORDENADOR','DISCENTE','PROFESSOR'),
        primary key (id)
    );

    create table pessoa (
        data_nascimento date,
        id bigint generated by default as identity,
        nome varchar(80) not null,
        cpf varchar(255),
        nacionalidade enum ('ARGENTINA','BRASILEIRA','CHILENA','ITALIANA','JAPONESA','NORTE_AMERICANA'),
        primary key (id)
    );
 
    create table usuario (
        id bigint generated by default as identity,
        img_perfil varchar(255),
        nome_perfil varchar(255),
        senha varchar(255),
        username varchar(255),
        primary key (id)
    );

    create table usuario_funcao_tab (
        id_funcao bigint not null,
        id_usuario bigint not null,
        primary key (id_funcao, id_usuario)
    );
 
    alter table if exists discente 
       add constraint FKmh2s5m3ikablx4ovb07ah3wvg 
       foreign key (id_pessoa) 
       references pessoa;

    alter table if exists usuario_funcao_tab 
       add constraint FKok5gp7l6j5dnmnkpwwdwxs374 
       foreign key (id_funcao) 
       references funcao;

    alter table if exists usuario_funcao_tab 
       add constraint FK8fn746xwkm1mlneygai6lnbqk 
       foreign key (id_usuario) 
       references usuario