create table fornecedor (
    id bigint generated by default as identity,
    nome varchar(255) not null,
    cnpj varchar(30),
    contato varchar(80),
    email varchar(120),
    telefone varchar(30),
    endereco varchar(255),
    data_cadastro date,
    primary key (id)
);

insert into fornecedor (nome, cnpj, contato, email, telefone, endereco, data_cadastro) values
('Fornecedor A','12.345.678/0001-90','João Silva','contato@fornecedora.com','(11)99999-0001','Rua A, 123','2025-10-05'),
('Fornecedor B','98.765.432/0001-55','Maria Souza','vendas@fornecedorb.com','(11)99999-0002','Av. B, 456','2025-09-01');
